footer:
  color: similar
  div: brush
  dots:
  - link: https://chat.whatsapp.com/DPbPJBRTk8pChDJBJP6q22
    icon: whatsapp
  - link: https://t.me/lagrantribunomada
    icon: telegram
  - link: https://www.instagram.com/lagrantribunomada/
  - link: https://www.youtube.com/@lagrantribunomada
